import { useNavigate } from "react-router";
import { BusinessStatusBadge } from "../../app/components/common/BusinessStatusBadge";
import { DesktopDataTable, MobileEntityCard, QuantityDisplay } from "../../app/components/common/BusinessPrimitives";
import { EmptyState, ErrorState, LoadingSkeleton } from "../../app/components/common/FeedbackStates";
import { SectionHeader } from "../../app/components/common/PageHeader";
import type { DashboardData } from "./dashboard.types";

const date = (value?: string | null) => value ? new Date(value).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "Not scheduled";
export function PendingDeliveriesSection({ dashboard }: { dashboard: DashboardData }) {
  const navigate = useNavigate(); if (!dashboard.canViewDeliveries) return null;
  const items = dashboard.deliveries.data.filter((item) => !["DELIVERED", "CANCELLED"].includes(item.status)).slice(0, 5);
  return <section className="space-y-3"><SectionHeader title="Pending Deliveries" description="Deliveries awaiting completion" action={<button onClick={() => navigate("/deliveries")} className="min-h-11 text-[14px] font-semibold text-blue-700">View all Deliveries</button>}/>{dashboard.deliveries.loading && !dashboard.deliveries.data.length ? <LoadingSkeleton/> : dashboard.deliveries.error ? <ErrorState message="Could not load deliveries." onRetry={dashboard.refresh}/> : !items.length ? <EmptyState title="No pending deliveries" description="All current deliveries have been completed."/> : <><div className="space-y-3 md:hidden">{items.map((item) => <MobileEntityCard key={item.id}><div className="flex items-start justify-between gap-3"><div><p className="text-[13px] font-semibold text-blue-700">{item.deliveryNumber}</p><h3 className="mt-1 break-words text-[15px] font-bold text-slate-950">{item.customerName}</h3></div><BusinessStatusBadge status={item.status}/></div><p className="mt-3 text-[14px] text-slate-700">{item.materialName}</p><div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-[13px] text-slate-600"><span><QuantityDisplay value={item.quantity} unit={item.unit}/></span><span>{date(item.scheduledDate)}</span>{item.vehicleNumber && <span>{item.vehicleNumber}</span>}</div></MobileEntityCard>)}</div><DesktopDataTable><table className="w-full text-left text-[14px]"><thead className="bg-slate-50 text-slate-600"><tr><th className="p-4">Delivery</th><th>Customer</th><th>Material</th><th>Quantity</th><th>Scheduled</th><th>Status</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-t border-slate-200"><td className="p-4 font-semibold">{item.deliveryNumber}</td><td>{item.customerName}</td><td>{item.materialName}</td><td><QuantityDisplay value={item.quantity} unit={item.unit}/></td><td>{date(item.scheduledDate)}</td><td><BusinessStatusBadge status={item.status}/></td></tr>)}</tbody></table></DesktopDataTable></>}</section>;
}
