import { ArrowDownToLine, ArrowUpFromLine } from "lucide-react";
import { DesktopDataTable, MobileEntityCard, QuantityDisplay } from "../../app/components/common/BusinessPrimitives";
import { EmptyState, ErrorState, LoadingSkeleton } from "../../app/components/common/FeedbackStates";
import { SectionHeader } from "../../app/components/common/PageHeader";
import type { StockTransactionData } from "../../api/inventory.api";
import type { DashboardData } from "./dashboard.types";

const isIn = (item: StockTransactionData) => ["IN", "TRANSFER_IN"].includes(item.type);
const label = (item: StockTransactionData) => isIn(item) ? "Stock In" : "Stock Out";
const dateTime = (value: string) => new Date(value).toLocaleString("en-IN", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });
const reason = (value?: string | null) => value ? value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase()) : "Stock adjustment";
export function RecentStockMovements({ dashboard }: { dashboard: DashboardData }) {
  const items = dashboard.movements.data.slice(0, 8);
  return <section className="space-y-3"><SectionHeader title="Recent Stock Movements" description="Latest stock added and removed"/>{dashboard.movements.loading && !items.length ? <LoadingSkeleton/> : dashboard.movements.error ? <ErrorState message="Could not load stock movements." onRetry={dashboard.refresh}/> : !items.length ? <EmptyState title="No stock movements yet" description="Stock In and Stock Out entries will appear here."/> : <><div className="space-y-3 md:hidden">{items.map((item) => { const Icon = isIn(item) ? ArrowDownToLine : ArrowUpFromLine; return <MobileEntityCard key={item.id}><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-lg ${isIn(item) ? "bg-green-50 text-green-800" : "bg-amber-50 text-amber-800"}`}><Icon size={19}/></span><div><p className="text-[13px] font-bold text-slate-600">{label(item)}</p><h3 className="mt-0.5 break-words text-[15px] font-bold text-slate-950">{item.inventoryItem?.materialName ?? "Material"}</h3></div></div><span className="shrink-0 text-[15px] font-bold text-slate-900">{isIn(item) ? "+" : "−"}<QuantityDisplay value={item.quantity} unit={item.inventoryItem?.unit}/></span></div><div className="mt-3 text-[13px] text-slate-600"><p>{item.godown?.name ?? "Godown not recorded"}</p><p>{reason(item.reason)}</p><time>{dateTime(item.createdAt)}</time></div></MobileEntityCard>; })}</div><DesktopDataTable><table className="w-full text-left text-[14px]"><thead className="bg-slate-50 text-slate-600"><tr><th className="p-4">Movement</th><th>Material</th><th>Quantity</th><th>Godown</th><th>Reason</th><th>Date</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-t border-slate-200"><td className="p-4 font-semibold">{label(item)}</td><td>{item.inventoryItem?.materialName ?? "Material"}</td><td className="font-semibold"><QuantityDisplay value={item.quantity} unit={item.inventoryItem?.unit}/></td><td>{item.godown?.name ?? "—"}</td><td>{reason(item.reason)}</td><td>{dateTime(item.createdAt)}</td></tr>)}</tbody></table></DesktopDataTable></>}</section>;
}
