import { AddressInfo } from "net";
import app from "../src/app";
import { prisma } from "../src/config/db";
import { generateToken } from "../src/utils/jwt";
const assert=(condition:unknown,message:string)=>{if(!condition)throw new Error(message)};

async function main(){
  const suffix=`${Date.now()}-${Math.random().toString(16).slice(2)}`,businessA=await prisma.business.create({data:{name:`Expense Test A ${suffix}`}}),businessB=await prisma.business.create({data:{name:`Expense Test B ${suffix}`}});
  try{
    const[owner,manager,staff,otherOwner]=await Promise.all([
      prisma.user.create({data:{name:"Expense Owner",email:`expense-owner-${suffix}@test.local`,passwordHash:"unused",role:"OWNER",businessId:businessA.id}}),
      prisma.user.create({data:{name:"Expense Manager",email:`expense-manager-${suffix}@test.local`,passwordHash:"unused",role:"MANAGER",businessId:businessA.id}}),
      prisma.user.create({data:{name:"Expense Staff",email:`expense-staff-${suffix}@test.local`,passwordHash:"unused",role:"STAFF",businessId:businessA.id}}),
      prisma.user.create({data:{name:"Other Owner",email:`expense-other-${suffix}@test.local`,passwordHash:"unused",role:"OWNER",businessId:businessB.id}}),
    ]);
    const server=app.listen(0);
    try{
      const port=(server.address()as AddressInfo).port,base=`http://127.0.0.1:${port}/api`,token=(u:{id:string;businessId:string;role:string})=>generateToken({userId:u.id,businessId:u.businessId,role:u.role});
      const call=async(method:string,path:string,user:typeof owner,body?:unknown)=>{const response=await fetch(`${base}${path}`,{method,headers:{authorization:`Bearer ${token(user)}`,"content-type":"application/json"},...(body===undefined?{}:{body:JSON.stringify(body)})});let json:any;try{json=await response.json()}catch{json=null}return{status:response.status,json}};
      const date=new Date().toISOString(),expense=(categoryId:string,overrides:Record<string,unknown>={})=>({expenseDate:date,categoryId,payee:"Test Vendor",amount:2000,gstApplicable:false,gstRate:0,paymentStatus:"PENDING",paymentMode:null,notes:"Isolated Phase 3.10 test",idempotencyKey:crypto.randomUUID(),...overrides});

      const categories1=await call("GET","/expense-categories",owner),categories2=await call("GET","/expense-categories",owner);assert(categories1.status===200&&categories1.json.data.length===12,"Default categories were not initialized");assert(categories2.json.data.length===12,"Default categories were duplicated");
      const categorySearch=await call("GET","/expense-categories?search=fuel",owner);assert(categorySearch.status===200&&categorySearch.json.data.length===1&&categorySearch.json.data[0].name==="Fuel","Category search failed");
      const custom=await call("POST","/expense-categories",owner,{name:"Site Security",description:"Security guard costs"});assert(custom.status===201,"OWNER category create failed");assert((await call("POST","/expense-categories",manager,{name:"Manager Category"})).status===201,"MANAGER category create failed");assert((await call("POST","/expense-categories",owner,{name:"  site security  "})).status===409,"Case-insensitive duplicate category was not rejected");

      const fuel=categories1.json.data.find((x:any)=>x.name==="Fuel"),paid=await call("POST","/expenses",manager,expense(fuel.id,{amount:1000,gstApplicable:true,gstRate:18,paymentStatus:"PAID",paymentMode:"BANK_TRANSFER",payee:"Fuel Station"}));assert(paid.status===201,"MANAGER paid expense create failed");assert(Number(paid.json.data.gstAmount)===180&&Number(paid.json.data.totalAmount)===1180,"GST calculation is incorrect");
      let ledger=await prisma.ledgerEntry.findMany({where:{businessId:businessA.id,referenceType:"EXPENSE",referenceId:paid.json.data.id}});assert(ledger.length===1&&ledger[0].transactionType==="EXPENSE_PAYMENT"&&Number(ledger[0].debitAmount)===1180,"Paid-at-creation did not create exactly one ledger entry");
      const pending=await call("POST","/expenses",owner,expense(custom.json.data.id));assert(pending.status===201,"OWNER pending expense create failed");assert(Number(pending.json.data.gstAmount)===0&&Number(pending.json.data.totalAmount)===2000,"Non-GST calculation is incorrect");assert(await prisma.ledgerEntry.count({where:{referenceType:"EXPENSE",referenceId:pending.json.data.id}})===0,"Pending expense created a ledger entry");
      const searchByNumber=await call("GET",`/expenses?search=${encodeURIComponent(pending.json.data.expenseNumber)}`,owner),filterByCategory=await call("GET",`/expenses?categoryId=${custom.json.data.id}`,owner);assert(searchByNumber.status===200&&searchByNumber.json.data.some((x:any)=>x.id===pending.json.data.id),"Expense search failed");assert(filterByCategory.status===200&&filterByCategory.json.data.some((x:any)=>x.id===pending.json.data.id),"Expense category filter failed");
      const marked=await call("POST",`/expenses/${pending.json.data.id}/mark-paid`,owner,{paymentMode:"UPI"});assert(marked.status===200&&marked.json.data.paymentStatus==="PAID","Mark Pending as Paid failed");assert(await prisma.ledgerEntry.count({where:{referenceType:"EXPENSE",referenceId:pending.json.data.id,transactionType:"EXPENSE_PAYMENT"}})===1,"Mark Paid did not create exactly one ledger entry");assert((await call("POST",`/expenses/${pending.json.data.id}/mark-paid`,owner,{paymentMode:"UPI"})).status===409,"Second Mark Paid was not rejected");

      const pendingCancel=await call("POST","/expenses",owner,expense(fuel.id,{amount:500,idempotencyKey:crypto.randomUUID()}));assert((await call("POST",`/expenses/${pendingCancel.json.data.id}/cancel`,manager,{reason:"Entered twice"})).status===200,"Pending cancellation failed");assert(await prisma.ledgerEntry.count({where:{referenceType:"EXPENSE",referenceId:pendingCancel.json.data.id}})===0,"Pending cancellation created a reversal");
      assert((await call("POST",`/expenses/${paid.json.data.id}/cancel`,owner,{reason:"   "})).status===400,"Empty cancellation reason was not rejected");const cancelledPaid=await call("POST",`/expenses/${paid.json.data.id}/cancel`,manager,{reason:"Duplicate fuel bill"});assert(cancelledPaid.status===200,"Paid expense cancellation failed");ledger=await prisma.ledgerEntry.findMany({where:{businessId:businessA.id,referenceType:"EXPENSE",referenceId:paid.json.data.id}});assert(ledger.length===2&&ledger.filter(x=>x.transactionType==="EXPENSE_PAYMENT_REVERSAL").length===1,"Paid cancellation did not create exactly one reversal");assert(ledger.reduce((sum,x)=>sum+Number(x.debitAmount)-Number(x.creditAmount),0)===0,"Expense ledger net did not return to zero");assert((await call("POST",`/expenses/${paid.json.data.id}/cancel`,owner,{reason:"Again"})).status===409,"Second cancellation was not rejected");

      const retainedCategory=await call("POST","/expense-categories",owner,{name:"Temporary Site Cost"}),retainedExpense=await call("POST","/expenses",owner,expense(retainedCategory.json.data.id,{amount:300,idempotencyKey:crypto.randomUUID()}));assert((await call("POST",`/expense-categories/${retainedCategory.json.data.id}/deactivate`,owner)).status===200,"Category deactivation failed");assert((await call("POST","/expenses",owner,expense(retainedCategory.json.data.id,{idempotencyKey:crypto.randomUUID()}))).status===400,"Inactive category was accepted for a new expense");const retained=await call("GET",`/expenses/${retainedExpense.json.data.id}`,staff);assert(retained.status===200&&retained.json.data.category.name==="Temporary Site Cost","Old expense did not retain inactive category display");

      const summary=await call("GET","/expenses/summary",owner);assert(summary.status===200&&Number(summary.json.data.totalPaid)===2000,"Expense summary did not exclude cancelled paid expense");assert(Number(summary.json.data.todayExpenses)===2300,"Today summary did not exclude cancelled expenses");
      const staffBody=expense(fuel.id,{idempotencyKey:crypto.randomUUID()});assert((await call("POST","/expenses",staff,staffBody)).status===403,"STAFF expense create did not return 403");assert((await call("PATCH",`/expenses/${retainedExpense.json.data.id}`,staff,{notes:"No"})).status===403,"STAFF edit did not return 403");assert((await call("POST",`/expenses/${retainedExpense.json.data.id}/mark-paid`,staff,{paymentMode:"CASH"})).status===403,"STAFF Mark Paid did not return 403");assert((await call("POST",`/expenses/${retainedExpense.json.data.id}/cancel`,staff,{reason:"No"})).status===403,"STAFF cancel did not return 403");assert((await call("POST","/expense-categories",staff,{name:"Forbidden"})).status===403,"STAFF category write did not return 403");
      assert((await call("GET",`/expenses/${retainedExpense.json.data.id}`,otherOwner)).status===404,"Cross-business read did not return 404");assert((await call("PATCH",`/expenses/${retainedExpense.json.data.id}`,otherOwner,{notes:"Cross tenant"})).status===404,"Cross-business update did not return 404");assert((await call("POST",`/expenses/${retainedExpense.json.data.id}/mark-paid`,otherOwner,{paymentMode:"CASH"})).status===404,"Cross-business Mark Paid did not return 404");assert((await call("POST",`/expenses/${retainedExpense.json.data.id}/cancel`,otherOwner,{reason:"Cross tenant"})).status===404,"Cross-business cancel did not return 404");const otherSummary=await call("GET","/expenses/summary",otherOwner);assert(otherSummary.status===200&&Object.values(otherSummary.json.data).every(Number.isInteger)&&Object.values(otherSummary.json.data).every(x=>x===0),"Cross-business summary leaked values");assert((await call("POST","/expenses",otherOwner,expense(fuel.id,{idempotencyKey:crypto.randomUUID()}))).status===400,"Business B used Business A category");
      console.log(JSON.stringify({success:true,checks:25,details:["OWNER pending create","MANAGER paid create","paid-at-create ledger","pending no ledger","Mark Paid ledger","duplicate Mark Paid 409","pending cancel no reversal","paid cancel reversal","duplicate cancel 409","blank reason 400","GST calculation","non-GST calculation","summary excludes cancelled","category search","expense search/filter","OWNER access","MANAGER access","STAFF writes 403","cross-business read 404","cross-business writes 404","duplicate category 409","inactive category rejected","inactive category retained on history","ledger nets zero","isolated data"]},null,2));
    }finally{await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()))}
  }finally{await prisma.business.deleteMany({where:{id:{in:[businessA.id,businessB.id]}}});await prisma.$disconnect()}
}
main().catch(error=>{console.error(error);process.exit(1)});
