import{AddressInfo}from"net";import app from"../src/app";import{prisma}from"../src/config/db";import{generateToken}from"../src/utils/jwt";const assert=(v:unknown,m:string)=>{if(!v)throw new Error(m)};
async function main(){const suffix=`${Date.now()}-${Math.random().toString(16).slice(2)}`,a=await prisma.business.create({data:{name:`Reports A ${suffix}`}}),b=await prisma.business.create({data:{name:`Reports B ${suffix}`}});try{const[owner,manager,staff,other]=await Promise.all([prisma.user.create({data:{name:"Owner",email:`r-o-${suffix}@t.local`,passwordHash:"x",role:"OWNER",businessId:a.id}}),prisma.user.create({data:{name:"Manager",email:`r-m-${suffix}@t.local`,passwordHash:"x",role:"MANAGER",businessId:a.id}}),prisma.user.create({data:{name:"Staff",email:`r-s-${suffix}@t.local`,passwordHash:"x",role:"STAFF",businessId:a.id}}),prisma.user.create({data:{name:"Other",email:`r-x-${suffix}@t.local`,passwordHash:"x",role:"OWNER",businessId:b.id}})]),customer=await prisma.customer.create({data:{customerCode:"C-1",name:"Report Customer",phone:"9999999999",creditLimit:2000,outstandingBalance:1180,businessId:a.id}}),otherCustomer=await prisma.customer.create({data:{customerCode:"C-2",name:"Other Customer",phone:"8888888888",businessId:b.id}}),supplier=await prisma.supplier.create({data:{supplierCode:"S-1",name:"Report Supplier",phone:"7777777777",paymentTerms:"30 days",totalPurchases:590,paidAmount:200,pendingPayments:390,businessId:a.id}}),godown=await prisma.godown.create({data:{godownCode:"G-1",name:"Main",businessId:a.id}}),costed=await prisma.inventoryItem.create({data:{materialName:"Costed Cement",category:"Cement",sku:"MAT-1",unit:"Bags",quantity:90,reorderLevel:20,location:"Main",costPrice:50,businessId:a.id}}),missing=await prisma.inventoryItem.create({data:{materialName:"Unknown Cost Item",category:"Other",sku:"MAT-2",unit:"Nos",quantity:5,reorderLevel:10,location:"Main",businessId:a.id}}),category=await prisma.expenseCategory.create({data:{name:"=Fuel",normalizedName:"=fuel",businessId:a.id,createdById:owner.id}}),now=new Date(),old=new Date(now.getTime()-100*86400000);
await prisma.stockTransaction.createMany({data:[{type:"IN",quantity:100,reason:"PURCHASE_RECEIPT",inventoryItemId:costed.id,godownId:godown.id,userId:owner.id,businessId:a.id},{type:"OUT",quantity:10,reason:"SALE",inventoryItemId:costed.id,godownId:godown.id,userId:owner.id,businessId:a.id},{type:"IN",quantity:5,reason:"OPENING_STOCK",inventoryItemId:missing.id,godownId:godown.id,userId:owner.id,businessId:a.id}]});
const invoiceData=(number:string,status:string,type:string,taxable:number,tax:number,total:number,balance:number,date=now)=>({invoiceNumber:number,invoiceDate:date,dueDate:date,status,invoiceType:type,customerId:customer.id,businessName:a.name,customerName:customer.name,customerPhone:customer.phone,taxableTotal:taxable,taxTotal:tax,totalAmount:total,amountPaid:total-balance,balanceDue:balance,businessId:a.id,createdById:owner.id});const gst=await prisma.invoice.create({data:{...invoiceData("INV-GST","ISSUED","GST",1000,180,1180,680,old),items:{create:{inventoryItemId:costed.id,materialName:costed.materialName,sku:costed.sku,unit:costed.unit,quantity:10,rate:100,grossAmount:1000,taxableAmount:1000,gstRate:18,cgstRate:9,sgstRate:9,cgstAmount:90,sgstAmount:90,lineTotal:1180}}}}),nonGst=await prisma.invoice.create({data:{...invoiceData("INV-NON","ISSUED","NON_GST",500,0,500,500),items:{create:{inventoryItemId:missing.id,materialName:missing.materialName,sku:missing.sku,unit:missing.unit,quantity:5,rate:100,grossAmount:500,taxableAmount:500,lineTotal:500}}}});await prisma.invoice.createMany({data:[invoiceData("INV-DRAFT","DRAFT","GST",300,54,354,354),invoiceData("INV-CANCEL","CANCELLED","GST",400,72,472,472)]});
const po=await prisma.purchaseOrder.create({data:{purchaseOrderNumber:"PO-1",orderDate:old,status:"RECEIVED",paymentStatus:"PARTIAL",supplierId:supplier.id,supplierName:supplier.name,supplierPhone:supplier.phone,taxableTotal:500,taxTotal:90,totalAmount:590,receivedAmount:590,amountPaid:200,balanceDue:390,businessId:a.id,createdById:owner.id,items:{create:{inventoryItemId:costed.id,godownId:godown.id,materialName:costed.materialName,sku:costed.sku,unit:costed.unit,quantity:10,receivedQuantity:10,rate:50,grossAmount:500,taxableAmount:500,gstRate:18,taxAmount:90,lineTotal:590}}},include:{items:true}});await prisma.purchaseOrder.create({data:{purchaseOrderNumber:"PO-X",status:"CANCELLED",supplierId:supplier.id,supplierName:supplier.name,supplierPhone:supplier.phone,totalAmount:1000,businessId:a.id,createdById:owner.id}});await prisma.purchaseReceipt.create({data:{receiptNumber:"GRN-1",receiptDate:now,totalAmount:590,idempotencyKey:crypto.randomUUID(),purchaseOrderId:po.id,supplierId:supplier.id,businessId:a.id,recordedById:owner.id,items:{create:{purchaseOrderItemId:po.items[0].id,inventoryItemId:costed.id,quantity:10,amount:590}}}});
const paid=await prisma.expense.create({data:{expenseNumber:"EXP-1",expenseDate:now,categoryId:category.id,payee:"=EVIL()",amount:200,gstApplicable:true,gstRate:18,gstAmount:36,totalAmount:236,paymentMode:"UPI",paymentStatus:"PAID",paidAt:now,createdById:owner.id,businessId:a.id}}),pending=await prisma.expense.create({data:{expenseNumber:"EXP-2",expenseDate:now,categoryId:category.id,amount:100,totalAmount:100,paymentStatus:"PENDING",createdById:owner.id,businessId:a.id}}),cancelled=await prisma.expense.create({data:{expenseNumber:"EXP-X",expenseDate:now,categoryId:category.id,amount:50,totalAmount:50,paymentStatus:"CANCELLED",cancelledAt:now,cancelledById:owner.id,cancellationReason:"Duplicate",createdById:owner.id,businessId:a.id}});await prisma.ledgerEntry.createMany({data:[{businessId:a.id,partyType:"BUSINESS",partyId:a.id,transactionType:"EXPENSE_PAYMENT",referenceType:"EXPENSE",referenceId:paid.id,amount:236,debitAmount:236,creditAmount:0,description:"Expense paid",createdById:owner.id,idempotencyKey:"E1"},{businessId:a.id,partyType:"BUSINESS",partyId:a.id,transactionType:"EXPENSE_PAYMENT",referenceType:"EXPENSE",referenceId:cancelled.id,amount:50,debitAmount:50,creditAmount:0,description:"Cancelled paid",createdById:owner.id,idempotencyKey:"E2"},{businessId:a.id,partyType:"BUSINESS",partyId:a.id,transactionType:"EXPENSE_PAYMENT_REVERSAL",referenceType:"EXPENSE",referenceId:cancelled.id,amount:50,debitAmount:0,creditAmount:50,description:"Reversal",createdById:owner.id,idempotencyKey:"E3"}]});await prisma.customerPayment.create({data:{paymentNumber:"CP-1",customerId:customer.id,invoiceId:gst.id,amount:500,paymentMethod:"UPI",businessId:a.id,receivedById:owner.id}});await prisma.purchasePayment.create({data:{paymentNumber:"PP-1",amount:200,paymentMode:"BANK",purchaseOrderId:po.id,supplierId:supplier.id,businessId:a.id,recordedById:owner.id}});
const server=app.listen(0);try{const port=(server.address()as AddressInfo).port,base=`http://127.0.0.1:${port}/api/reports`,tok=(u:any)=>generateToken({userId:u.id,businessId:u.businessId,role:u.role}),call=async(path:string,u:any)=>{const r=await fetch(`${base}${path}`,{headers:{authorization:`Bearer ${tok(u)}`}}),text=await r.text();let json:any;try{json=JSON.parse(text)}catch{}return{status:r.status,json,text,headers:r.headers}},range=`from=${new Date(now.getFullYear(),0,1).toISOString()}&to=${now.toISOString()}`;
const sales=await call(`/sales?${range}`,owner);assert(sales.status===200&&sales.json.summary.totalSales===1680,"Sales total mismatch");assert(sales.json.summary.invoiceCount===2,"Draft/cancelled invoice included");assert(sales.json.summary.gstSales===1180&&sales.json.summary.nonGstSales===500,"GST sales split incorrect");assert(sales.json.summary.taxableAmount===1500,"Taxable revenue incorrect");assert((await call(`/sales?${range}&limit=1`,owner)).json.pagination.pages===2,"Pagination failed");
const purchases=await call(`/purchases?${range}`,manager);assert(purchases.status===200&&purchases.json.summary.orderedPurchaseValue===590&&purchases.json.summary.receivedPurchaseValue===590,"Purchase values incorrect or cancelled included");const inv=await call(`/inventory?${range}`,staff);assert(inv.status===200&&inv.json.rows.find((x:any)=>x.id===costed.id).openingQuantity===0&&inv.json.rows.find((x:any)=>x.id===costed.id).discrepancy===0,"Inventory reconciliation failed");const valuation=await call("/stock-valuation",owner);assert(valuation.json.summary.totalStockValue===4500&&valuation.json.summary.missingCostItems===1,"Valuation or missing cost incorrect");assert(valuation.json.rows.find((x:any)=>x.id===costed.id).valuationMethod==="LAST_PURCHASE_COST","Valuation method incorrect");
const customers=await call("/customer-outstanding",owner);assert(customers.json.summary.totalReceivable===1180,"Customer outstanding mismatch");assert(customers.json.breakdowns.aging.some((x:any)=>x.name==="90+"&&x.total>=680),"Customer aging incorrect");const suppliers=await call(`/supplier-outstanding?${range}`,owner);assert(suppliers.json.summary.totalPayable===390,"Supplier outstanding mismatch");assert(suppliers.json.breakdowns.aging.some((x:any)=>x.name==="61-90"&&x.total===390),"Supplier aging incorrect");
const expenses=await call(`/expenses?${range}`,staff);assert(expenses.status===200&&expenses.json.summary.totalExpenses===336&&expenses.json.summary.gstOnExpenses===36,"Expense totals/GST incorrect");const gstReport=await call(`/gst-summary?${range}`,owner);assert(gstReport.json.summary.salesGst.outputGst===180&&gstReport.json.summary.expenseGst.inputGst===36,"GST summary incorrect");const pl=await call(`/profit-loss?${range}`,owner);assert(pl.json.summary.revenue===1500,"GST was included in revenue");assert(pl.json.summary.estimatedCogs===500&&pl.json.summary.operatingExpenses===200,"P&L incorrectly used purchases/payments");assert(pl.json.metadata.isEstimated&&pl.json.metadata.warnings.some((x:string)=>x.includes("excluded from COGS")),"Missing-cost estimate warning absent");assert(await prisma.ledgerEntry.aggregate({where:{referenceId:cancelled.id},_sum:{debitAmount:true,creditAmount:true}}).then(x=>Number(x._sum.debitAmount)-Number(x._sum.creditAmount))===0,"Reversal did not neutralize ledger");
assert((await call(`/overview?${range}`,owner)).status===200&&await call(`/overview?${range}`,manager).then(x=>x.status)===200,"OWNER/MANAGER report access failed");assert((await call(`/profit-loss?${range}`,staff)).status===403&&(await call("/gst-summary",staff)).status===403,"STAFF accessed restricted report");const otherSales=await call(`/sales?${range}`,other);assert(otherSales.status===200&&otherSales.json.summary.totalSales===0,"Cross-business totals leaked");assert((await call(`/sales?${range}&customerId=${otherCustomer.id}`,owner)).status===404,"Cross-business filter was accepted");
const csv=await call(`/expenses?${range}&format=csv`,owner);assert(csv.status===200&&csv.headers.get("content-type")?.includes("text/csv"),"CSV export failed");assert(csv.text.includes("EXP-1")&&!csv.text.includes("EXP-X"),"CSV did not respect filters");assert(csv.text.includes("'=EVIL()")&&csv.text.includes("'=Fuel"),"CSV formula injection not neutralized");assert(sales.json.metadata.generatedAt&&sales.json.metadata.currency==="INR","Report metadata missing");console.log(JSON.stringify({success:true,checks:30,details:["sales reconciliation","draft/cancel exclusion","GST split","purchase ordered/received","cancelled purchase exclusion","inventory reconciliation","valuation method","missing cost","customer outstanding","customer aging","supplier outstanding","supplier aging","expense exclusion","expense GST","GST cancellation exclusion","revenue excludes GST","payments excluded from revenue","supplier payments excluded from expenses","COGS not purchases","P&L warning","OWNER access","MANAGER access","STAFF restriction","tenant totals","tenant filters","CSV filters","CSV injection","pagination","metadata","ledger reversal"]},null,2));}finally{await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()))}
}finally{
  try {
    await prisma.ledgerEntry.deleteMany({where:{businessId:{in:[a.id,b.id]}}});
    await prisma.expense.deleteMany({where:{businessId:{in:[a.id,b.id]}}});
    await prisma.customerPayment.deleteMany({where:{businessId:{in:[a.id,b.id]}}});
    await prisma.purchaseReceipt.deleteMany({where:{businessId:{in:[a.id,b.id]}}});
    await prisma.purchaseOrder.deleteMany({where:{businessId:{in:[a.id,b.id]}}});
    await prisma.invoice.deleteMany({where:{businessId:{in:[a.id,b.id]}}});
    await prisma.stockTransaction.deleteMany({where:{businessId:{in:[a.id,b.id]}}});
    await prisma.inventoryItem.deleteMany({where:{businessId:{in:[a.id,b.id]}}});
    await prisma.godown.deleteMany({where:{businessId:{in:[a.id,b.id]}}});
    await prisma.user.deleteMany({where:{businessId:{in:[a.id,b.id]}}});
  } catch (err) {}
  await prisma.business.deleteMany({where:{id:{in:[a.id,b.id]}}});
  await prisma.$disconnect()}}
main().catch(e=>{console.error(e);process.exit(1)});
