import { useState } from "react";
import { Check } from "lucide-react";

const tabs = [
  { label: "Dashboard", src: "/dashboard.png" },
  { label: "Inventory", src: "/inventory.png" },
  { label: "Billing", src: "/billing.png" },
  { label: "Reports", src: "/reports.png" },
  { label: "Warehouse", src: "/warehouse.png" },
];

export default function ProductShowcaseSection(){const [active,setActive]=useState(0);const tab=tabs[active];return <section id="showcase" className="relative overflow-hidden bg-gradient-to-br from-white to-orange-50/60 py-24"><div className="absolute -right-28 bottom-0 h-80 w-80 rounded-full bg-orange-100/60 blur-3xl"/><div className="relative mx-auto max-w-[1240px] px-5 sm:px-8"><div className="text-center"><p className="text-[10px] font-black uppercase tracking-[.22em] text-orange-500">A workspace your team can learn quickly</p><h2 className="mt-4 text-3xl font-black text-slate-900 sm:text-4xl">Built for Speed and Ease of Use</h2></div><div className="mt-12 grid gap-10 lg:grid-cols-[.34fr_.66fr] lg:items-center"><div><p className="text-sm font-medium leading-7 text-slate-600">A clear interface for the work your team does every day—without complex menus or duplicate entries.</p><div className="mt-6 space-y-3">{["Real-time business overview","Fast sales and purchase entry","Low-stock and collection alerts","Role-based access for your team"].map(text=><p key={text} className="flex items-center gap-2 text-sm font-bold text-slate-700"><span className="grid h-5 w-5 place-items-center rounded-full bg-emerald-100 text-emerald-600"><Check size={12}/></span>{text}</p>)}</div></div><div><div className="mb-4 flex gap-2 overflow-x-auto pb-2" role="tablist" aria-label="ERP product screenshots">{tabs.map((item,index)=><button key={item.label} type="button" role="tab" aria-selected={active===index} onClick={()=>setActive(index)} className={`shrink-0 rounded-full px-4 py-2 text-[10px] font-extrabold transition ${active===index?"bg-orange-500 text-white shadow-lg shadow-orange-500/20":"border border-slate-200 bg-white text-slate-600 hover:border-orange-200 hover:text-orange-600"}`}>{item.label}</button>)}</div><div className="group overflow-hidden rounded-2xl border border-white/90 bg-white/70 p-2 shadow-[0_32px_74px_-30px_rgba(15,23,42,.42)] ring-1 ring-slate-200/70 backdrop-blur-xl sm:p-3"><div className="mb-2 flex h-8 items-center gap-1.5 border-b border-slate-100 px-2"><i className="h-2 w-2 rounded-full bg-red-300"/><i className="h-2 w-2 rounded-full bg-amber-300"/><i className="h-2 w-2 rounded-full bg-emerald-300"/><b className="ml-2 text-[8px] text-slate-500">APNI ESTATE · {tab.label}</b></div><div className="overflow-hidden rounded-xl bg-slate-50"><img key={tab.label} src={tab.src} alt={`APNI ESTATE ${tab.label} ERP screen`} onError={(event)=>{event.currentTarget.onerror=null;event.currentTarget.src="/dashboard.png";}} className="product-shot-fade block h-auto w-full transition duration-700 ease-out group-hover:scale-[1.015]" loading="lazy" decoding="async"/></div></div></div></div></div></section>}
