import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { expenseCategoryApi } from "../../api/expense.api";
import { PageHeader } from "../../app/components/common/PageHeader";
import { ConfirmDialog } from "../../app/components/common/ConfirmDialog";
import type { ExpenseCategory } from "../../features/expenses/expense.types";
import { useAuth } from "../../hooks/useAuth";
import { hasPermission } from "../../utils/permissions";
export default function ExpenseCategoriesPage(){
  const{user}=useAuth(),canManage=hasPermission(user,"expense-categories:manage"),[data,setData]=useState<ExpenseCategory[]>([]),[search,setSearch]=useState(""),[editing,setEditing]=useState<ExpenseCategory|null>(null),[name,setName]=useState(""),[description,setDescription]=useState(""),[deactivating,setDeactivating]=useState<ExpenseCategory|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const load=()=>expenseCategoryApi.list("active=all").then(r=>setData(r.data)).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);const visible=useMemo(()=>data.filter(x=>!search||`${x.name} ${x.description||""}`.toLowerCase().includes(search.toLowerCase())),[data,search]);
  const open=(row?:ExpenseCategory)=>{setEditing(row||({id:"",name:"",isActive:true,isDefault:false}));setName(row?.name||"");setDescription(row?.description||"")},save=async()=>{if(!editing||!name.trim()||busy)return;setBusy(true);try{editing.id?await expenseCategoryApi.update(editing.id,{name,description}):await expenseCategoryApi.create({name,description});toast.success(editing.id?"Category updated":"Category added");setEditing(null);await load()}catch(e){toast.error(e instanceof Error?e.message:"Category could not be saved.")}finally{setBusy(false)}},deactivate=async()=>{if(!deactivating||busy)return;setBusy(true);try{await expenseCategoryApi.deactivate(deactivating.id);toast.success("Category deactivated");setDeactivating(null);await load()}catch(e){toast.error(e instanceof Error?e.message:"Category could not be deactivated.")}finally{setBusy(false)}};
  return <div className="space-y-5"><PageHeader title="Expense Categories" description="Organize expenses using simple categories." actions={canManage&&<button onClick={()=>open()} className="min-h-12 rounded-lg bg-blue-700 px-4 font-semibold text-white">Add Category</button>}/>{error&&<p className="rounded-lg bg-red-50 p-3 text-red-800">{error}</p>}<input aria-label="Search categories" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search categories" className="h-12 w-full rounded-lg border bg-white px-3 md:max-w-md"/><div className="grid gap-3 md:grid-cols-2">{visible.map(x=><article key={x.id} className="rounded-xl border bg-white p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{x.name}</h2>{x.isDefault&&<span className="rounded-full bg-blue-50 px-2 py-0.5 text-xs font-bold text-blue-700">DEFAULT</span>}{!x.isActive&&<span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold">INACTIVE</span>}</div><p className="mt-1 text-sm text-slate-500">{x.description||"No description"}</p><p className="mt-2 text-xs text-slate-500">Used by {x._count?.expenses||0} expenses</p></div>{canManage&&<div className="flex gap-1"><button onClick={()=>open(x)} className="min-h-11 px-3 font-semibold text-blue-700">Edit</button>{x.isActive&&<button onClick={()=>setDeactivating(x)} className="min-h-11 px-3 font-semibold text-red-700">Deactivate</button>}</div>}</div></article>)}</div>{editing&&<div className="fixed inset-0 z-[100] flex items-end justify-center bg-slate-950/45 sm:items-center sm:p-4"><div className="w-full rounded-t-2xl bg-white p-5 sm:max-w-md sm:rounded-2xl"><h2 className="text-xl font-bold">{editing.id?"Edit Category":"Add Category"}</h2><label className="mt-4 block text-sm font-semibold">Category Name<input autoFocus required value={name} onChange={e=>setName(e.target.value)} className="mt-2 h-12 w-full rounded-lg border px-3"/></label><label className="mt-4 block text-sm font-semibold">Description<textarea value={description} onChange={e=>setDescription(e.target.value)} className="mt-2 min-h-24 w-full rounded-lg border p-3"/></label><div className="mt-5 flex gap-2"><button disabled={busy} onClick={()=>setEditing(null)} className="min-h-11 flex-1 rounded-lg border font-semibold">Cancel</button><button disabled={!name.trim()||busy} onClick={save} className="min-h-11 flex-[2] rounded-lg bg-blue-700 font-semibold text-white disabled:opacity-60">{busy?"Saving…":"Save Category"}</button></div></div></div>}<ConfirmDialog open={!!deactivating} title={`Deactivate ${deactivating?.name}?`} description="Old expenses will keep this category, but it cannot be used for new expenses." confirmLabel={busy?"Please wait…":"Deactivate"} destructive onCancel={()=>!busy&&setDeactivating(null)} onConfirm={deactivate}/></div>;
}
