import { useEffect, useState } from "react";
import { Link, useParams } from "react-router";
import { toast } from "sonner";
import { expenseApi } from "../../api/expense.api";
import { BusinessStatusBadge } from "../../app/components/common/BusinessStatusBadge";
import { ExpenseActionDialog } from "../../features/expenses/ExpenseActionDialog";
import type { Expense } from "../../features/expenses/expense.types";
import { useAuth } from "../../hooks/useAuth";
import { fmt } from "../../utils/currency";
import { hasPermission } from "../../utils/permissions";
export default function ExpenseDetailsPage(){
  const{id=""}=useParams(),{user}=useAuth(),[expense,setExpense]=useState<Expense|null>(null),[error,setError]=useState(""),[action,setAction]=useState<"pay"|"cancel"|null>(null),[value,setValue]=useState(""),[busy,setBusy]=useState(false),canManage=hasPermission(user,"expenses:manage");
  const load=()=>expenseApi.get(id).then(r=>setExpense(r.data)).catch(e=>setError(e.message));useEffect(()=>{void load()},[id]);
  const run=async()=>{if(!action||!value.trim()||busy)return;setBusy(true);try{action==="pay"?await expenseApi.markPaid(id,value):await expenseApi.cancel(id,value.trim());toast.success(action==="pay"?"Expense marked as paid":"Expense cancelled");setAction(null);setValue("");await load()}catch(e){toast.error(e instanceof Error?e.message:"Expense could not be updated.")}finally{setBusy(false)}};
  if(error)return <div className="rounded-xl bg-red-50 p-5 text-red-800">{error}<button onClick={load} className="ml-3 font-bold">Retry</button></div>;if(!expense)return <div className="h-64 animate-pulse rounded-xl bg-slate-200"/>;
  return <div className="mx-auto max-w-4xl space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link to="/expenses" className="text-sm font-semibold text-blue-700">← Expenses</Link><div className="mt-2 flex items-center gap-3"><h1 className="text-2xl font-bold md:text-3xl">{expense.expenseNumber}</h1><BusinessStatusBadge status={expense.paymentStatus}/></div><p className="mt-1 text-slate-600">{expense.category.name} · {new Date(expense.expenseDate).toLocaleDateString("en-IN")}</p></div>{canManage&&expense.paymentStatus!=="CANCELLED"&&<div className="flex flex-wrap gap-2"><Link to={`/expenses/${id}/edit`} className="flex min-h-11 items-center rounded-lg border px-4 font-semibold">Edit</Link>{expense.paymentStatus==="PENDING"&&<button onClick={()=>{setValue("");setAction("pay")}} className="min-h-11 rounded-lg bg-blue-700 px-4 font-semibold text-white">Mark as Paid</button>}<button onClick={()=>{setValue("");setAction("cancel")}} className="min-h-11 rounded-lg border border-red-200 px-4 font-semibold text-red-700">Cancel Expense</button></div>}</div>
  <section className="rounded-xl border bg-white p-5 md:p-7"><p className="text-sm text-slate-500">Total Expense</p><p className="mt-1 text-4xl font-bold text-slate-950">{fmt(expense.totalAmount)}</p><div className="mt-6 grid gap-4 border-t pt-5 sm:grid-cols-2"><Info label="Payee">{expense.payee||"—"}</Info><Info label="Base Amount">{fmt(expense.amount)}</Info><Info label="GST Rate">{expense.gstApplicable?`${expense.gstRate}%`:"Not applicable"}</Info><Info label="GST Amount">{fmt(expense.gstAmount)}</Info><Info label="Payment Status">{expense.paymentStatus}</Info><Info label="Payment Method">{expense.paymentMode?.replaceAll("_"," ")||"—"}</Info><Info label="Created By">{expense.createdBy.name}</Info><Info label="Created Date">{new Date(expense.createdAt).toLocaleString("en-IN")}</Info>{expense.paidAt&&<Info label="Paid Date">{new Date(expense.paidAt).toLocaleString("en-IN")}</Info>}{expense.attachmentUrl&&<Info label="Attachment"><a href={expense.attachmentUrl} target="_blank" rel="noreferrer" className="text-blue-700">Open Link</a></Info>}</div>{expense.notes&&<div className="mt-5 border-t pt-5"><p className="text-sm text-slate-500">Notes</p><p className="mt-1 whitespace-pre-wrap">{expense.notes}</p></div>}{expense.paymentStatus==="CANCELLED"&&<div className="mt-5 rounded-lg bg-red-50 p-4 text-red-800"><b>Cancelled</b><p className="mt-1">{expense.cancellationReason}</p><p className="mt-1 text-xs">{expense.cancelledAt&&new Date(expense.cancelledAt).toLocaleString("en-IN")} · {expense.cancelledBy?.name}</p></div>}</section>
  {!!expense.ledgerEntries?.length&&<section className="rounded-xl border bg-white p-5"><h2 className="text-lg font-bold">Ledger History</h2><div className="mt-3 space-y-2">{expense.ledgerEntries.map(row=><div key={row.id} className="flex justify-between gap-3 border-t py-3"><div><b>{row.transactionType.replaceAll("_"," ")}</b><p className="text-sm text-slate-500">{row.description}</p></div><div className="text-right"><b>{Number(row.debitAmount)>0?`−${fmt(row.debitAmount)}`:`+${fmt(row.creditAmount)}`}</b><p className="text-xs text-slate-500">{new Date(row.transactionDate).toLocaleDateString("en-IN")}</p></div></div>)}</div></section>}
  {action&&<ExpenseActionDialog type={action} value={value} onChange={setValue} busy={busy} onCancel={()=>!busy&&setAction(null)} onConfirm={run}/>}</div>;
}
function Info({label,children}:{label:string;children:React.ReactNode}){return <div><p className="text-sm text-slate-500">{label}</p><div className="mt-1 font-semibold">{children}</div></div>}
