export enum UserRole {
  OWNER = "OWNER",
  MANAGER = "MANAGER",
  STAFF = "STAFF",
  DRIVER = "DRIVER",
}

export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  [UserRole.OWNER]: [
    "dashboard:view",
    "inventory:view",
    "inventory:create",
    "inventory:update",
    "inventory:delete",
    "stock:in",
    "stock:out",
    "sales:view",
    "sales:manage",
    "deliveries:view",
    "deliveries:manage",
    "trips:view_assigned",
    "trips:view_all",
    "trips:manage",
    "vehicles:view",
    "vehicles:manage",
    "drivers:view",
    "drivers:manage",
    "ledger:view",
    "reports:view",
    "team:manage",
    "business:manage",
    "delivery:update_status",
    "delivery:upload_proof",
  ],
  [UserRole.MANAGER]: [
    "dashboard:view",
    "inventory:view",
    "inventory:create",
    "inventory:update",
    "inventory:delete",
    "stock:in",
    "stock:out",
    "sales:view",
    "sales:manage",
    "deliveries:view",
    "deliveries:manage",
    "trips:view_assigned",
    "trips:view_all",
    "trips:manage",
    "vehicles:view",
    "vehicles:manage",
    "drivers:view",
    "drivers:manage",
    "ledger:view",
    "reports:view",
    "delivery:update_status",
    "delivery:upload_proof",
  ],
  [UserRole.STAFF]: [
    "inventory:view",
    "stock:in",
    "stock:out",
    "sales:view",
    "deliveries:view",
    "delivery:update_status",
    "delivery:upload_proof",
  ],
  [UserRole.DRIVER]: [
    "trips:view_assigned",
    "delivery:update_status",
    "delivery:upload_proof",
    "vehicles:view",
  ],
};
