export enum UserRole {
  OWNER = "OWNER",
  MANAGER = "MANAGER",
  STAFF = "STAFF",
  DRIVER = "DRIVER",
}

export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  [UserRole.OWNER]: [
    "dashboard:view",
    "inventory:view",
    "inventory:create",
    "inventory:update",
    "inventory:delete",
    "stock:in",
    "stock:out",
    "sales:view",
    "sales:manage",
    "purchases:view",
    "purchases:manage",
    "deliveries:view",
    "deliveries:manage",
    "deliveries:create",
    "deliveries:dispatch",
    "deliveries:complete",
    "deliveries:cancel",
    "deliveries:reverse",
    "trips:view_assigned",
    "trips:view_all",
    "trips:manage",
    "vehicles:view",
    "vehicles:manage",
    "drivers:view",
    "drivers:manage",
    "ledger:view",
    "financials:view", "financials:manage",
    "expenses:view", "expenses:manage", "expense-categories:manage",
    "reports:view",
    "reports:operational", "reports:financial",
    "team:manage",
    "business:manage",
    "customers:view", "customers:create", "customers:update", "customers:delete",
    "suppliers:view", "suppliers:create", "suppliers:update", "suppliers:delete",
    "godowns:view", "godowns:create", "godowns:update", "godowns:transfer",
    "delivery:update_status",
    "delivery:upload_proof",
    "sales-returns:view", "sales-returns:create", "sales-returns:update",
    "purchase-returns:view", "purchase-returns:create", "purchase-returns:update",
  ],
  [UserRole.MANAGER]: [
    "dashboard:view",
    "inventory:view",
    "inventory:create",
    "inventory:update",
    "inventory:delete",
    "stock:in",
    "stock:out",
    "sales:view",
    "sales:manage",
    "purchases:view",
    "purchases:manage",
    "deliveries:view",
    "deliveries:manage",
    "deliveries:create",
    "deliveries:dispatch",
    "deliveries:complete",
    "deliveries:cancel",
    "trips:view_assigned",
    "trips:view_all",
    "trips:manage",
    "vehicles:view",
    "vehicles:manage",
    "drivers:view",
    "drivers:manage",
    "ledger:view",
    "financials:view", "financials:manage",
    "expenses:view", "expenses:manage", "expense-categories:manage",
    "reports:view",
    "reports:operational", "reports:financial",
    "customers:view", "customers:create", "customers:update", "customers:delete",
    "suppliers:view", "suppliers:create", "suppliers:update", "suppliers:delete",
    "godowns:view", "godowns:create", "godowns:update", "godowns:transfer",
    "delivery:update_status",
    "delivery:upload_proof",
    "sales-returns:view", "sales-returns:create", "sales-returns:update",
    "purchase-returns:view", "purchase-returns:create", "purchase-returns:update",
  ],
  [UserRole.STAFF]: [
    "inventory:view",
    "stock:in",
    "stock:out",
    "sales:view",
    "purchases:view",
    "deliveries:view",
    "delivery:update_status",
    "delivery:upload_proof",
    "customers:view",
    "suppliers:view",
    "godowns:view",
    "financials:view", "ledger:view",
    "expenses:view",
    "reports:operational",
    "sales-returns:view", "sales-returns:create",
    "purchase-returns:view", "purchase-returns:create",
  ],
  [UserRole.DRIVER]: [
    "trips:view_assigned",
    "delivery:update_status",
    "delivery:upload_proof",
    "vehicles:view",
  ],
};
